GET https://api.finmindtrade.com/api/v4/data
    ?dataset=TaiwanExchangeRate
    &data_id=USD
    &start_date=2021-09-13
    &token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRlIjoiMjAyNC0wMS0wMiAxNTowODoyMyIsInVzZXJfaWQiOiIxN2tvYmUiLCJpcCI6IjIxMC43MS4yMTcuMjUxIn0.Dl5cEreMFOqT_4rrpwHwApyVn6vrEovKPMP3-zygpHk

###
GET https://api.finmindtrade.com/api/v4/data
    ?dataset=TaiwanStockPriceTick
    &data_id=0056
    &token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRlIjoiMjAyNC0wMS0wMiAxNTowNTowMSIsInVzZXJfaWQiOiIxN2tvYmUiLCJpcCI6IjIxMC43MS4yMTcuMjUxIn0.dUfqWFbtrTWC6gSMhux6IB_tAS3hvGzj278CPXBn6d8

###
GET https://api.finmindtrade.com/api/v4/data
    ?dataset=TaiwanStockPrice
    &data_id=0056
    &start_date=2021-09-13
    &token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRlIjoiMjAyNC0wMS0wMiAxNTowNTowMSIsInVzZXJfaWQiOiIxN2tvYmUiLCJpcCI6IjIxMC43MS4yMTcuMjUxIn0.dUfqWFbtrTWC6gSMhux6IB_tAS3hvGzj278CPXBn6d8

###
GET https://api.finmindtrade.com/api/v4/data
    ?dataset=TaiwanStockDividend
    &data_id=2885
    &start_date=2021-01-13
    &token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRlIjoiMjAyNC0wMS0wMiAxNTowODoyMyIsInVzZXJfaWQiOiIxN2tvYmUiLCJpcCI6IjIxMC43MS4yMTcuMjUxIn0.Dl5cEreMFOqT_4rrpwHwApyVn6vrEovKPMP3-zygpHk

###
GET https://api.finmindtrade.com/api/v4/data
    ?dataset=TaiwanStockPER
    &data_id=2330
    &start_date=2020-01-13
    &token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRlIjoiMjAyNC0wMS0wMiAxNTowODoyMyIsInVzZXJfaWQiOiIxN2tvYmUiLCJpcCI6IjIxMC43MS4yMTcuMjUxIn0.Dl5cEreMFOqT_4rrpwHwApyVn6vrEovKPMP3-zygpHk


###
GET https://api.finmindtrade.com/api/v4/data
    ?dataset=TaiwanExchangeRate
    &data_id=USD
    &start_date=2022-02-26
    &token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRlIjoiMjAyNC0wMS0wMiAxNTowODoyMyIsInVzZXJfaWQiOiIxN2tvYmUiLCJpcCI6IjIxMC43MS4yMTcuMjUxIn0.Dl5cEreMFOqT_4rrpwHwApyVn6vrEovKPMP3-zygpHk

###
GET https://api.finmindtrade.com/api/v4/data
    ?dataset=TaiwanStockDividend
    &data_id=2330
    &start_date=2021-01-13
 

###
GET https://tw.stock.yahoo.com/_td-stock/api/resource/FundServices.fundsPriceHistory;fundId=F00000VTAH:FO;timeslot=2012-03-28T00:00:00Z-2022-03-29T23:59:59Z?bkt=&device=desktop&ecma=modern&feature=ecmaModern,useVersionSwitch,useNewQuoteTabColor&intl=tw&lang=zh-Hant-TW&partner=none&prid=e4nof9lh3r54p&region=TW&site=finance&tz=Asia/Taipei&ver=1.2.1233&returnMeta=true

###
GET https://api.tej.com.tw/api/datatables/TRAIL/TAOFNAV.json?api_key=BrGJpJFVIZlm32yC1KZHTqoqn8ocSZ

###
GET https://query1.finance.yahoo.com/v8/finance/chart/2330.TW?period1=0&period2=1549258857&interval=1d&events=history&=hP2rOschxO0